version: '3.4'
services:
  mirex:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /home
    volumes:
      - ./home:/home
      - ./footprint:/footprint
      - ${WORKING_DIR}/cache:/cache
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
       - discovery.type=single-node
       - indices.query.bool.max_clause_count=1000000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${FOOTPRINT_DB_FOLDER}:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
