#!/bin/bash

# example
# ./matcher test/file_list_for_query_small.txt ./test/dir_for_db ./test/result.txt

# to run elasticsearch only:
#FOOTPRINT_DB_FOLDER=./test/dir_for_db docker-compose up -d elasticsearch

file_list_for_query=$1
path_for_db=$2

export FOOTPRINT_DB_FOLDER=$path_for_db/es_data
docker-compose down
docker-compose up -d elasticsearch

rm -rf ./tmp/queries
mkdir -p ./tmp/queries/audios
touch ./tmp/queries/query_map.csv
echo "key,file" >> ./tmp/queries/query_map.csv

n=1
while read line; do
  $(find ffmpeg-git* -type d | head -n 1)/ffmpeg -nostdin -i '$line' -acodec pcm_s16le -ac 1 -ar 44100 './tmp/queries/audios/$n.wav'
  n=$((n+1))
  echo "$line,/cache/queries/audios/$n.wav" >> ./tmp/queries/query_map.csv
done < $file_list_for_query


docker-compose run --rm mirex python3 match.py

cp './tmp/results.txt' $3
cat $3
